//! Checks the code against the Lean models proved in `verify/`, via the vectors
//! they generate (`verify/vectors.json`, regenerated by `verify/check.sh`).

use chrono::{DateTime, Duration, TimeZone, Utc};
use serde::Deserialize;

use crate::cache::{self, Mode};
use crate::model::{ProviderState, Snapshot, Usage, Window};
use crate::{codex, format};

#[derive(Deserialize)]
struct Vectors {
    countdown: Vec<(i64, String)>,
    ago: Vec<(i64, String)>,
    /// `(percent as f64 bits, width, bar)`
    bar: Vec<(u64, usize, String)>,
    refresh: Vec<Refresh>,
    codex: Vec<Codex>,
}

#[derive(Deserialize)]
struct Refresh {
    cached: Option<i64>,
    last: Option<i64>,
    now: i64,
    mode: String,
    source: String,
    fetch: bool,
}

/// Windows are `(limit_window_seconds, used_percent, reset_at)`, results `(used_percent, reset_at)`.
#[derive(Deserialize)]
struct Codex {
    primary: Option<(u64, u64, i64)>,
    secondary: Option<(u64, u64, i64)>,
    five_hour: Option<(u64, i64)>,
    weekly: Option<(u64, i64)>,
}

fn vectors() -> Vectors {
    serde_json::from_str(include_str!("../verify/vectors.json")).unwrap()
}

#[test]
fn countdown_matches_model() {
    for (s, want) in vectors().countdown {
        assert_eq!(
            format::countdown(Duration::seconds(s)),
            want,
            "countdown({s}s)"
        );
    }
}

#[test]
fn ago_matches_model() {
    for (s, want) in vectors().ago {
        assert_eq!(format::ago(Duration::seconds(s)), want, "ago({s}s)");
    }
}

#[test]
fn bar_matches_model() {
    for (bits, width, want) in vectors().bar {
        let percent = f64::from_bits(bits);
        assert_eq!(format::bar(percent, width), want, "bar({percent}, {width})");
    }
}

#[test]
fn refresh_matches_model() {
    let t0 = Utc.with_ymd_and_hms(2026, 9, 23, 12, 0, 0).unwrap();
    let at = |s: i64| t0 + Duration::seconds(s);
    // The claude field tells which snapshot was chosen when nothing is fetched;
    // the codex fetch fails, so its field tells it even when fetching.
    let snapshot = |attempted: Option<i64>, pct: f64| {
        let state = ProviderState {
            usage: Some(usage(pct)),
            error: None,
        };
        Snapshot {
            claude: state.clone(),
            codex: state,
            attempted_at: attempted.map(at),
        }
    };
    for v in vectors().refresh {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("c.json");
        if v.cached.is_some() {
            let cached = serde_json::to_string(&snapshot(v.cached, 1.0)).unwrap();
            std::fs::write(&path, cached).unwrap();
        }
        let mode = match v.mode.as_str() {
            "auto" => Mode::Auto,
            _ => Mode::Manual,
        };
        let refreshed = cache::refresh(
            &path,
            || at(v.now),
            mode,
            snapshot(v.last, 2.0),
            || Ok(usage(3.0)),
            || Err(anyhow::anyhow!("down")),
        );
        let snap = refreshed.snapshot;
        let case = format!(
            "cached={:?} last={:?} now={} {}",
            v.cached, v.last, v.now, v.mode
        );
        // With no cache file the cached snapshot is the empty default.
        let source_usage = match (v.source.as_str(), v.cached) {
            ("last", _) => Some(usage(2.0)),
            (_, Some(_)) => Some(usage(1.0)),
            (_, None) => None,
        };
        assert_eq!(snap.codex.usage, source_usage, "source: {case}");
        let fetched = snap.claude.usage == Some(usage(3.0));
        assert_eq!(fetched, v.fetch, "fetch: {case}");
        if v.fetch {
            assert_eq!(snap.attempted_at, Some(at(v.now)), "{case}");
        }
    }
}

#[test]
fn codex_classification_matches_model() {
    let window = |w: Option<(u64, u64, i64)>| {
        w.map_or("null".to_string(), |(len, pct, reset)| {
            format!(r#"{{"used_percent":{pct},"limit_window_seconds":{len},"reset_at":{reset}}}"#)
        })
    };
    let expected = |w: Option<(u64, i64)>| {
        w.map(|(pct, reset)| Window {
            used_percent: pct as f64,
            resets_at: DateTime::from_timestamp(reset, 0),
        })
    };
    for v in vectors().codex {
        let body = format!(
            r#"{{"rate_limit":{{"primary_window":{},"secondary_window":{}}}}}"#,
            window(v.primary),
            window(v.secondary)
        );
        let want = Usage {
            five_hour: expected(v.five_hour),
            weekly: expected(v.weekly),
        };
        assert_eq!(codex::parse(&body).unwrap(), want, "{body}");
    }
}

fn usage(pct: f64) -> Usage {
    Usage {
        five_hour: Some(Window {
            used_percent: pct,
            resets_at: None,
        }),
        weekly: None,
    }
}
